import { User, FitnessGoal, UserRole } from '../../domain/entities/User';
import { IUserRepository } from '../../domain/repositories/IUserRepository';
import { CreateUserDTO } from '../dtos/CreateUserDTO';
import { DuplicateEntityError, RequiredFieldError } from '../../domain/errors/DomainError';

export class CreateUserUseCase {
  constructor(private userRepository: IUserRepository) {}

  async execute(dto: CreateUserDTO): Promise<User> {
    // Validate input
    if (!dto.email) throw new RequiredFieldError('email', 'User');
    if (!dto.name) throw new RequiredFieldError('name', 'User');
    if (!dto.fitnessGoal) throw new RequiredFieldError('fitnessGoal', 'User');

    // Check if user with email already exists
    const existingUser = await this.userRepository.findByEmail(dto.email);
    if (existingUser) {
      throw new DuplicateEntityError('User', 'email', dto.email);
    }

    // Create user with required parameters in the correct order
    const user = User.create(
      '', // id will be generated by the repository
      dto.name,
      dto.email,
      new Date(), // Pass the Date object directly
      dto.fitnessGoal,
      dto.isManager ? UserRole.MANAGER : UserRole.USER
    );

    return await this.userRepository.save(user);
  }
}
